### ISSUE TITLE
Is there variables/placeholders support?

### ISSUE THREAD

**Issue by iyesin** [victor-rds/KeeTrayTOTP#12]
Hello.

I'm actively using keepass2 with `Kee` (from firefox/chromium side) and `this` plugin.
I want to enable auto-fill of _one-time authentication codes_.
Most recommendations says to use `{TOTP}` placeholder as Form field value and copy name and id from form parameters. I tried to follow such guides — it doesn't work for me.
Any recommendations?
Where I can find list of supported/exported variables?

**Comment by Sanaki** [comment]
Simple answer: Currently not supported, conversation exists (but isn't moving much) at https://forum.kee.pm/t/kee-and-otp-codes/1037.

**Comment by Sanaki** [comment]
This is now fully supported in the current stable release of Kee and KeepassRPC. Info and (WIP) instructions: https://forum.kee.pm/t/placeholder-handling/1100

Self-made instructions (I could have missed something here):
You'll need to add the TOTP fields to Kee's id/field listing in the browser plugin's configuration. Different sites will likely use different field IDs, since TOTP doesn't seem to have any standardized field name. (If you need that ID, right click the field itself and inspect element to see the code that defined it.) Once you've added it there, go to the specific entry you want to enable TOTP entry through in keepass. Kee tab, form fields section, add. Name can be anything (I just name these all TOTP), ID is the field ID, Value (assuming you haven't changed KeeTrayTOTP's default placeholder in settings) is {TOTP}. Make sure you click the Enabled radio for use of placeholders with this entry.

**Comment by iyesin** [comment]
@Sanaki thank you! Works like a charm with KeePassRPC 1.8.0.0
